name: CI — Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    name: Backend — Spring Boot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build backend
        working-directory: taskmanager-backend
        run: mvn clean compile -q --no-transfer-progress

      - name: Run backend tests
        working-directory: taskmanager-backend
        run: mvn test -q --no-transfer-progress
        env:
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

  frontend:
    name: Frontend — React
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: taskmanager-frontend
        run: npm install

      - name: Build frontend
        working-directory: taskmanager-frontend
        run: npm run build
